import type { User, Hackathon, Article } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 1,
    name: 'Priya Sharma',
    college: 'Stanford University',
    email: 'priya@stanford.edu',
    avatarUrl: 'https://i.pravatar.cc/150?img=1',
    skills: ['React', 'TypeScript', 'Node.js', 'GraphQL'],
    github: 'https://github.com/priya',
  },
  {
    id: 2,
    name: 'Ben Carter',
    college: 'MIT',
    email: 'ben@mit.edu',
    avatarUrl: 'https://i.pravatar.cc/150?img=2',
    skills: ['Python', 'Django', 'PostgreSQL', 'Docker'],
    linkedin: 'https://linkedin.com/in/ben',
  },
  {
    id: 3,
    name: 'Chloe Davis',
    college: 'UC Berkeley',
    email: 'chloe@berkeley.edu',
    avatarUrl: 'https://i.pravatar.cc/150?img=3',
    skills: ['UI/UX Design', 'Figma', 'Prototyping', 'User Research'],
    linkedin: 'https://linkedin.com/in/chloe',
  },
  {
    id: 4,
    name: 'Leo Rodriguez',
    college: 'Georgia Tech',
    email: 'leo@gatech.edu',
    avatarUrl: 'https://i.pravatar.cc/150?img=4',
    skills: ['AI/ML', 'PyTorch', 'TensorFlow', 'Data Science'],
    github: 'https://github.com/leo',
  },
];


export const MOCK_HACKATHONS: Hackathon[] = [
  // Upcoming
  {
    id: 1,
    title: 'AI for Social Good',
    organizer: 'Innovate Org',
    theme: 'Artificial Intelligence',
    image: 'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=800',
    description: 'Join us for a 3-day hackathon focused on leveraging AI to solve pressing social issues. We are looking for creative minds in machine learning, data science, and software development to build innovative solutions for a better world. Workshops and mentorship from industry experts will be provided.',
    registrationStart: '15/9',
    registrationEnd: '25/9',
    eventStart: '2/10',
    eventEnd: '10/10',
    status: 'Upcoming',
    registerLink: '#',
    requiredSkills: ['AI/ML', 'Python', 'React', 'Firebase'],
  },
  {
    id: 2,
    title: 'FinTech Challenge',
    organizer: 'Capital Bank',
    theme: 'Finance',
    image: 'https://images.unsplash.com/photo-1554260570-e9682a3418b2?q=80&w=800',
    description: 'Disrupt the world of finance in our annual FinTech Challenge. We are calling all developers, designers, and business strategists to innovate in areas like blockchain, digital payments, and algorithmic trading. Compete for cash prizes and internship opportunities.',
    registrationStart: '20/9',
    registrationEnd: '30/9',
    eventStart: '15/10',
    eventEnd: '17/10',
    status: 'Upcoming',
    registerLink: '#',
    requiredSkills: ['Node.js', 'Cybersecurity', 'Solidity', 'UI/UX Design'],
  },
  {
    id: 3,
    title: 'Sustainable Earth Hack',
    organizer: 'GreenTech Foundation',
    theme: 'Sustainability',
    image: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?q=80&w=800',
    description: 'Code for a greener planet. This hackathon is dedicated to creating technology that addresses environmental challenges, from renewable energy solutions to waste reduction systems. We welcome participants from all backgrounds who are passionate about sustainability.',
    registrationStart: '1/10',
    registrationEnd: '10/10',
    eventStart: '22/10',
    eventEnd: '24/10',
    status: 'Upcoming',
    registerLink: '#',
    requiredSkills: ['IoT', 'Data Science', 'GIS', 'Mobile Dev'],
  },
  // Ongoing
  {
    id: 4,
    title: 'HealthTech Connect',
    organizer: 'Wellness Corp',
    theme: 'Healthcare',
    image: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?q=80&w=800',
    description: 'Innovate at the intersection of health and technology. This event focuses on developing solutions for telemedicine, electronic health records, and personalized medicine. Collaborate with healthcare professionals and tech experts to make a difference.',
    registrationStart: '1/9',
    registrationEnd: '10/9',
    eventStart: '12/9',
    eventEnd: '14/9',
    status: 'Ongoing',
    registerLink: '#',
    requiredSkills: ['Swift', 'Kotlin', 'FHIR', 'UI/UX Design'],
  },
  {
    id: 5,
    title: 'GameDev Jam 2024',
    organizer: 'Pixel Studios',
    theme: 'Gaming',
    image: 'https://images.unsplash.com/photo-1580327344181-c1163234e5a0?q=80&w=800',
    description: 'Create the next hit game in just 48 hours! Join fellow game developers, artists, and sound designers in a fun, fast-paced environment. All platforms and engines are welcome. Show off your creativity and win amazing prizes from our sponsors.',
    registrationStart: '5/9',
    registrationEnd: '10/9',
    eventStart: '11/9',
    eventEnd: '15/9',
    status: 'Ongoing',
    registerLink: '#',
    requiredSkills: ['Unity', 'C#', 'Blender', 'Game Design'],
  },
  // Past
  {
    id: 6,
    title: 'Code for Education',
    organizer: 'LearnHub',
    theme: 'EdTech',
    image: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?q=80&w=800',
    description: 'This hackathon focused on building open-source tools to improve access to education worldwide. Teams developed platforms for remote learning, interactive textbooks, and student collaboration tools.',
    registrationStart: '1/8',
    registrationEnd: '10/8',
    eventStart: '15/8',
    eventEnd: '17/8',
    status: 'Past',
    registerLink: '#',
    requiredSkills: ['React', 'Firebase', 'Node.js'],
  },
  {
    id: 7,
    title: 'Future of Mobility',
    organizer: 'Auto Innovators',
    theme: 'Automotive',
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=800',
    description: 'Participants at this event tackled challenges in the automotive industry, including autonomous driving, electric vehicle infrastructure, and connected car services. The winning team created a predictive maintenance system using machine learning.',
    registrationStart: '15/7',
    registrationEnd: '25/7',
    eventStart: '1/8',
    eventEnd: '3/8',
    status: 'Past',
    registerLink: '#',
    requiredSkills: ['C++', 'ROS', 'Computer Vision'],
  },
];

export const MOCK_ARTICLES: Article[] = [
    { id: 1, title: "The Rise of AI in Software Development", source: "TechCrunch", link: "#", publishedDate: "2 days ago" },
    { id: 2, title: "A Deep Dive into Quantum Computing", source: "Wired", link: "#", publishedDate: "3 days ago" },
    { id: 3, title: "Is Web3 the Future of the Internet?", source: "The Verge", link: "#", publishedDate: "4 days ago" },
    { id: 4, title: "Sustainable Tech: Innovations for a Greener Planet", source: "MIT Tech Review", link: "#", publishedDate: "5 days ago" },
    { id: 5, title: "How to Build a Scalable Microservices Architecture", source: "InfoQ", link: "#", publishedDate: "1 week ago" },
    { id: 6, title: "Next.js 14: What's New?", source: "Vercel Blog", link: "#", publishedDate: "1 week ago" },
    { id: 7, title: "Understanding Large Language Models", source: "AI Weekly", link: "#", publishedDate: "2 weeks ago" },
];
